baseURL = "https://janasabino.github.io/"
defaultContentLanguage = "fr"
theme = "nomad-tech"
disableKinds = ["rss"]

capitalizeListTitles = false

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[languages]
  [languages.fr]
    locale = "fr-FR"
    label = "Français"
    title = "Janaina Sabino"
    weight = 1

[params]
  author = "Janaina"
  logo = "Janaina Sabino"
  subtitle = "Ingénierie pédagogique • Intelligence artificielle • Qualité & Qualiopi"
  description = "Je pars des besoins et des difficultés d’apprentissage pour concevoir des solutions pédagogiques adaptées au contexte, aux objectifs et aux réalités du terrain."



 