baseURL = "https://janasabino.github.io/"
defaultContentLanguage = "fr"
theme = "nomad-tech"
disableKinds = ["rss"]

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[languages]
  [languages.fr]
    locale = "fr-FR"
    label = "Français"
    title = "Janaina Sabino"
    weight = 1

[params]
  author = "Janaina"
  logo = "Janaina Sabino"
  subtitle = "Ingénierie pédagogique • Intelligence artificielle"
  description = "J’accompagne les projets de formation, de l’analyse des besoins à la conception, en mobilisant l’intelligence artificielle au service de la pédagogie."



 